### ISSUE TITLE
Agriculture and Attorney General are being swapped after being selected from drop-down menu

### ISSUE THREAD

**Issue by najsaqib** [bcgov/WES_engagement_states#14]
Currently looking into it to trace the source of the issue.

**Comment by daattali** [comment]
Huh, strange! We shouldn't both spend time on this, so I won't spend any effort for now. Let me know if you stop looking into it and I should take over

**Comment by daattali** [comment]
I see the same issue with "Public Guardian and Trustee" and "Office of the Premier"

**Comment by najsaqib** [comment]
I actually spent some time looking into it this morning but I couldn't identify the issue. Maybe you'll have an easier time of it?

**Comment by daattali** [comment]
Sure I'll tackle

**Comment by daattali** [comment]
Good catch! That was 100% my fault

**Comment by najsaqib** [comment]
Awesome!
