### ISSUE TITLE
Deploying the app

### ISSUE THREAD

**Issue by daattali** [bcgov/WES_engagement_states#20]
@najsaqib @MonkmanMH 

I was just on call with @jimmartell @kelpisland and @ateucher and they discussed the current state of deploying BC Gov shiny apps.  Are we ready to deploy this app publicly at its current state? This doesn't have to mean it's at its final version, we can always re-deploy when there's updated code/data

**Comment by najsaqib** [comment]
@daattali @MonkmanMH @jimmartell 

I spoke with Angela not too long ago about the app. Barring some minor things here and there, she was generally very satisfied with the state of the app as it stands. We will most certainly have to re-deploy it in the future as we replace the mock data with actual data (and deal with all the associated issues, such as #19 and #15 ). 

I personally feel that we should go ahead with deploying the app right now just so we can establish that side of the workflow for subsequent deployments. Of course there might still be some issues that @MonkmanMH and @jimmartell are aware of with the app in particular or the deployment process in general that might lead them to disagree though.

**Comment by kelpisland** [comment]
Hi Dean, and all,

I agree, the deployment work is the critical path. Once successful on OpenShift all follow on deployments are literally a button press. This allows work to continue incrementally with CD to a test project and easy promotes to Prod.

T

Sent from my iPhone

On Jan 24, 2017, at 9:04 AM, Najmus Saqib <notifications@github.com<mailto:notifications@github.com>> wrote:


@daattali<https://github.com/daattali> @MonkmanMH<https://github.com/MonkmanMH> @jimmartell<https://github.com/jimmartell>

I spoke with Angela not too long ago about the app. Barring some minor things here and there, she was generally very satisfied with the state of the app as it stands. We will most certainly have to re-deploy it in the future as we replace the mock data with actual data (and deal with all the associated issues).

I personally feel that we should go ahead with deploying the app right now just so we can establish that side of the workflow for subsequent deployments. Of course there might still be some issues that @MonkmanMH<https://github.com/MonkmanMH> and @jimmartell<https://github.com/jimmartell> are aware of with the app in particular or the deployment process in general that might lead them to disagree though.

-

**Comment by jimmartell** [comment]
This is great news. Eager to proceed with deployment asap.

**Comment by daattali** [comment]
OK looks like we got the thumbs up to begin trying to deploy this app, will update when there are news

**Comment by kelpisland** [comment]
Great - coordinate with Shea if you need any help with OpenShift, and Andy is a great resource as well!

T

Sent from my iPhone

On Jan 24, 2017, at 10:15 PM, Dean Attali <notifications@github.com<mailto:notifications@github.com>> wrote:


OK looks like we got the thumbs up to begin trying to deploy this app, will update when there are news

-

**Comment by daattali** [comment]
@najsaqib @MonkmanMH can I clean up the top level directory of this repo? There are a bunch of files there that I didn't create and some of them look like they're a WIP, so I don't want to delete anything that's not mine without asking first, but I'm fairly certain it's safe to delete everything outside the `shiny` folder

**Comment by daattali** [comment]
Note to self: a working `packages.txt` file for the deployment config can be: 

```
'ggplot2', 'dplyr', 'tidyr', 'DT', 'networkD3', 'readr', 'knitr', 'tidyverse', 'car', 'pander'
```

**Comment by najsaqib** [comment]
@daattali I also think it is safe to clean up the top level directory in the repo if need be. I don't see anything essential in there myself.

**Comment by ateucher** [comment]
You'll need to inspect those R packages for the necessary system dependencies all the way down. I know at least that `xml2` needs `libxml2-dev`

**Comment by daattali** [comment]
This repo should now work with the docker deployment. However, that doesn't mean it's deployed - I'm not sure how to get it into openshift and onto a public URL
