### ISSUE TITLE
migration plot fix

### ISSUE THREAD

**Issue by ateucher** [bcgov/WES_engagement_states#22]
`networkD3::sankeyNetwork()` has apparently been updated to use d3v4. As such, `d3.scale.ordinal` in [this line](https://github.com/bcgov/WES-engagement-states/blob/master/app/server-helpers.R#L105) needs to be changed to `d3.scaleOrdinal`.

**Comment by daattali** [comment]
Awesome, thanks for the heads up Andy

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>
