### ISSUE TITLE
Engagement bubble plot: interactive vs static

### ISSUE THREAD

**Issue by daattali** [bcgov/WES_engagement_states#5]
I spent some time trying to convert the static ggplot2 engagement plot into an interactive plot, but it seems like there are simply no packages that are as powerful as ggplot2. Everything I try that supports interactivity has some problems. Try again later!

**Comment by daattali** [comment]
Unfortunately it seems like ggplot2 is still a few levels above all other visualization packages, and it's impossible to recreate the same plot in an interactive environment.  The closest I could get is using the following code (using `plotly` package, the biggest disadvantage here is that the legend doesn't get generated)

```
layout(ggplotly(ggplot(
    data,
    aes(x = Commitment, y = Satisfaction,
        text = paste0(Engagement.State, " (", Percent, "%)"), text2 = Satisfaction, text3 = Commitment,
        fill = Engagement.State)) +
        geom_vline(xintercept = mean_commitment, col = "#555555") +
        geom_hline(yintercept = mean_satisfaction, col = "#555555") +
        geom_point(aes(size = Percent), 
                   shape = 21, colour = "black", alpha=0.9) +
        scale_size_area(max_size = 30, guide = FALSE) + 
        xlim(0, 120) + ylim(0, 120) +
        scale_fill_manual(values = PLOT_COLS) +
        theme_bw(26) +
        guides(fill = guide_legend("Engagement State",
                                   override.aes = list(size = 4))) +
        theme(legend.key = element_blank(), panel.grid.minor = element_blank(),
              legend.key.height = unit(1.5, "line")),
         tooltip=c("text", "text2", "text3")),
      showlegend = FALSE) %>%
    config(displayModeBar = 'hover', displaylogo = FALSE) %>%
    layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
```

**Comment by najsaqib** [comment]
I was playing around with the Plotly package for this bubble chart and I couldn't figure out a way to format the legend so that all the bubble elements were the same size. Is that the problem you encountered as well? Below is what I inevitably ended up with:
![bubblechart](https://cloud.githubusercontent.com/assets/22086214/19173244/3af9996a-8bdb-11e6-994c-a0d727aaccd3.png)

**Comment by daattali** [comment]
Yes I had that too, that's why I explicitly suppressed the legend, because of that bug. It is indeed a bug, I spoke with the guy who develops plotly, but it doesn't seem like it'll be fixed any time soon.  I've tried several different interactive visualization packages, none of them seem to be able to support the same plot that ggplot2 generates. Not even ggvis (which is the new package developed by Hadley).  

However, if you really want to use plotly and suppress the legend, that can be ok - the legend can be created manually with HTML.

**Comment by najsaqib** [comment]
Interesting. It is certainly unfortunate that the author won't be able to fix the bug anytime soon. Would have been ideal if the legend functioned as intended.

In the meanwhile, I personally think that we should be OK with what is there already (i.e. the bubble plot generated with ggplot2). Maybe @MonkmanMH can chime in with his opinion on this. If we do not need to exactly replicate the previous iterations of the bubble plot, maybe other packages such as rCharts  or Plotly can still be utilized for this purpose.

**Comment by daattali** [comment]
I was able to get a minimal reproducible example so I filed an official bug report https://github.com/ropensci/plotly/issues/755

Ultimately it's a judgment call - prioritize an informative plot, or interactivity? I usually vote for interactivity myself, but in this specific case since there's so few data points on the plot I don't think there's too much added value to interactivity, which is why I chose to stick with the static plot.

**Comment by daattali** [comment]
Update: the plot is currently minimally interactive - hovering over a bubble shows its size. But this comes at the cost of the labels, plots, and bubble sizes being the wrong size and the plot doesn't look as nice as with plain static ggplot2 (in my opinion!).

**Comment by daattali** [comment]
Another update: in commit https://github.com/bcgov/WES-engagement-states/commit/7af4a0d862fd8e82b98e834218bd79046bc0c598 I removed the interactivity because the new ggplot2 v2.2.0 requires an updated version of ggiraph, which in turn requires D3.js v4, which breaks Sankey plots from networkD3 since they still use D3 v3

When `networkD3` updates their code to support D3 v4, we can use `ggiraph` again

**Comment by najsaqib** [comment]
In commit a8f4551c1506f62c0dfc4ea65fb5a42bcf793ad2, I have modified the look of the bubble chart to match some newer documents produced within BC Stats. One of the changes is the addition of the labels, which, in effect, renders the tool-tip functionality added by `ggiraph` redundant. It would certainly be neat to re-introduce `ggiraph` back into the code when `networkD3` is updated, but for the time being, I think we can make do without it.
